name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # Använd rätt version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Payment-Service.Api/Payment-Service.Api.csproj

      # Build the application
      - name: Build
        run: dotnet build Payment-Service.Api/Payment-Service.Api.csproj --configuration Release --no-restore

      # Test application (valfritt steg)
      # - name: Run tests
      #   run: dotnet test MenuService.Tests/MenuService.Tests.csproj --no-build --verbosity normal

      # Logga in på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bygg Docker-image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Payment-Service.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/payment-service:latest
